### ISSUE TITLE
Remove not valid lines from the end of CSV

### ISSUE THREAD

**Issue by ujovlado** [davidesner/keboola-bingads-ex#1]
Hi David,

we're running into small issue while importing data to our Storage API.

Problem is that some of the CSVs (probably all) contain some kind of Copyright Notice at the end. Thus these CSVs are not valid.

Sample end of CSV file:

``` csv
"value1","value2","value3"
"value1","value2","value3"
"value1","value2","value3"

"©2016 Microsoft Corporation. All rights reserved. "
```

Would it be possible to remove these "not valid" CSV lines? For example, keep all non empty lines with exact column count?

Many Thanks!

**Comment by davidesner** [comment]
Hi. The issue was related with results returned by the report service queries only. I have deployed already a fix. All lines with different column count are removed from the end of the file now.
